on:
  release:
    types: [published]
name: Release
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 23.6
        uses: actions/setup-node@v2
        with:
          node-version: 23.6
      - run: npm ci
      - run: sudo snap install snapcraft --classic
      - run: npm run build:linux -- --publish always
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
