on: [push, pull_request]
name: Test
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 23.6
        uses: actions/setup-node@v2
        with:
          node-version: 23.6
      - run: npm ci
      - run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 23.6
        uses: actions/setup-node@v2
        with:
          node-version: 23.6
      - run: npm ci
      - run: npm test
